import { useState } from 'react';
import { MdAutorenew, MdPerson, MdFileDownload } from 'react-icons/md';
import { JOURNAL_ENTRIES, MONTHLY_SUMMARY } from '@/mocks/journal';
import { useScenario } from '@/context/ScenarioContext';

const TYPE_COLORS: Record<string, string> = {
  '진단': 'bg-red-100 text-red-700',
  '관수': 'bg-blue-100 text-blue-700',
  '방제': 'bg-orange-100 text-orange-700',
  '수확': 'bg-green-100 text-green-700',
  '관찰': 'bg-purple-100 text-purple-700',
  '행정': 'bg-amber-100 text-amber-700',
  '기상': 'bg-cyan-100 text-cyan-700',
};

export default function JournalPage() {
  const { currentDay } = useScenario();
  const [filter, setFilter] = useState<string>('all');

  const visibleEntries = JOURNAL_ENTRIES
    .filter(e => new Date(e.date).getDate() <= currentDay)
    .filter(e => filter === 'all' || e.type === filter)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  const filterTypes = ['all', '진단', '관수', '방제', '기상', '행정', '관찰'];

  return (
    <div className="space-y-6">
      {/* Monthly Summary */}
      <div className="card bg-gradient-to-r from-orange-50 to-amber-50">
        <h3 className="section-title mb-3">{MONTHLY_SUMMARY.month} 요약</h3>
        <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
          <div className="text-center">
            <p className="text-2xl font-bold text-blue-600">{MONTHLY_SUMMARY.totalIrrigations}</p>
            <p className="text-xs text-gray-500">관수</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-bold text-red-600">{MONTHLY_SUMMARY.totalDiagnoses}</p>
            <p className="text-xs text-gray-500">진단</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-bold text-cyan-600">{MONTHLY_SUMMARY.weatherAlertsHandled}</p>
            <p className="text-xs text-gray-500">기상 대응</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-bold text-amber-600">{MONTHLY_SUMMARY.documentsGenerated}</p>
            <p className="text-xs text-gray-500">서류</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-bold text-gray-700">{MONTHLY_SUMMARY.journalEntries}</p>
            <p className="text-xs text-gray-500">총 기록</p>
          </div>
        </div>

        <div className="mt-4">
          <p className="text-sm font-medium text-gray-600 mb-1">주요 성과</p>
          <ul className="space-y-1">
            {MONTHLY_SUMMARY.highlights.slice(0, 3).map((h, i) => (
              <li key={i} className="text-sm text-gray-600 flex items-start gap-1">
                <span className="text-success">✓</span> {h}
              </li>
            ))}
          </ul>
        </div>

        <button className="btn-accent mt-4 w-full sm:w-auto">
          <MdFileDownload /> 보험 증빙 내보내기
        </button>
      </div>

      {/* Filters */}
      <div className="flex gap-2 overflow-x-auto pb-2">
        {filterTypes.map(f => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap cursor-pointer transition-colors ${
              filter === f
                ? 'bg-primary text-white'
                : 'bg-white text-gray-600 border border-gray-200 hover:bg-gray-50'
            }`}
          >
            {f === 'all' ? '전체' : f}
          </button>
        ))}
      </div>

      {/* Timeline */}
      <div className="space-y-0">
        {visibleEntries.map((entry, i) => {
          const showDate = i === 0 || visibleEntries[i - 1].date !== entry.date;

          return (
            <div key={entry.id}>
              {showDate && (
                <div className="flex items-center gap-3 py-2">
                  <span className="text-sm font-bold text-gray-400">
                    {new Date(entry.date).toLocaleDateString('ko-KR', { month: 'long', day: 'numeric' })}
                  </span>
                  <div className="flex-1 h-px bg-gray-200" />
                </div>
              )}

              <div className="flex gap-4 relative">
                {/* Timeline dot & line */}
                <div className="flex flex-col items-center">
                  <div className={`w-3 h-3 rounded-full ${entry.isAutoGenerated ? 'bg-primary' : 'bg-gray-400'} z-10`} />
                  {i < visibleEntries.length - 1 && (
                    <div className="w-0.5 flex-1 bg-gray-200" />
                  )}
                </div>

                {/* Entry Card */}
                <div className="flex-1 pb-4">
                  <div className="p-4 rounded-xl bg-white border border-gray-100">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className={`badge text-xs ${TYPE_COLORS[entry.type] || 'bg-gray-100 text-gray-600'}`}>
                        {entry.type}
                      </span>
                      {entry.isAutoGenerated ? (
                        <span className="flex items-center gap-1 text-xs text-primary">
                          <MdAutorenew className="text-sm" /> 자동 생성
                        </span>
                      ) : (
                        <span className="flex items-center gap-1 text-xs text-gray-400">
                          <MdPerson className="text-sm" /> 수동 기록
                        </span>
                      )}
                      {entry.sourceModule && (
                        <span className="text-xs text-gray-300">
                          {entry.sourceModule}
                        </span>
                      )}
                    </div>
                    <h4 className="font-semibold text-gray-900 mt-2">{entry.title}</h4>
                    <p className="text-sm text-gray-600 mt-1">{entry.description}</p>

                    {entry.sensorSnapshot && (
                      <div className="flex gap-3 mt-2 text-xs text-gray-500">
                        {entry.sensorSnapshot.soilMoisture != null && (
                          <span>습도 {entry.sensorSnapshot.soilMoisture}%</span>
                        )}
                        {entry.sensorSnapshot.temperature != null && (
                          <span>온도 {entry.sensorSnapshot.temperature}°C</span>
                        )}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
