export interface FarmerProfile {
  id: string;
  name: string;
  age: number;
  farmName: string;
  region: string;
  crops: CropInfo[];
  registrationDate: string;
  phone: string;
  insuranceId: string;
  avatar: string;
}

export interface CropInfo {
  name: string;
  variety: string;
  areaPyeong: number;
}

// Diagnosis
export interface DiagnosisResult {
  id: string;
  cropName: string;
  pestName: string;
  severity: '경증' | '중증' | '심각';
  affectedArea: string;
  confidence: number;
  imageUrl: string;
  treatmentId: string;
  timestamp: string;
  guardrailTriggered: boolean;
}

export interface TreatmentRecommendation {
  id: string;
  method: string;
  registeredPesticides: PesticideInfo[];
  applicationTiming: string;
  safetyPeriod: string;
  mixingNotes: string;
}

export interface PesticideInfo {
  name: string;
  dosage: string;
  interval: string;
}

// IoT Sensors
export interface SensorReading {
  timestamp: string;
  soilMoisture: number;
  temperature: number;
  humidity: number;
  lightIntensity: number;
}

export interface IrrigationEvent {
  id: string;
  triggeredAt: string;
  reason: string;
  valveAction: '열림' | '닫힘';
  duration: number;
  autoTriggered: boolean;
}

export interface SensorAlert {
  id: string;
  type: 'moisture' | 'temperature' | 'humidity' | 'connection';
  severity: '정보' | '주의' | '경고' | '위험';
  message: string;
  timestamp: string;
  resolved: boolean;
}

// Reviews
export interface Review {
  id: string;
  platform: '네이버스마트스토어' | '쿠팡';
  text: string;
  rating: number;
  date: string;
  sentiment: 'positive' | 'negative' | 'neutral';
}

export interface SentimentSummary {
  positive: number;
  negative: number;
  neutral: number;
  total: number;
}

export interface KeywordData {
  word: string;
  count: number;
  sentiment: 'positive' | 'negative' | 'neutral';
}

export interface AIStrategy {
  id: string;
  title: string;
  description: string;
  priority: '높음' | '중간' | '낮음';
}

// Documents
export interface DocumentTemplate {
  id: string;
  name: string;
  description: string;
  requiredFields: DocumentField[];
}

export interface DocumentField {
  fieldName: string;
  fieldType: 'text' | 'number' | 'date' | 'select';
  label: string;
  isAvailableFromProfile: boolean;
  value?: string;
}

export interface SubsidyMatch {
  id: string;
  name: string;
  eligibilityScore: number;
  deadline: string;
  amount: string;
  requirements: string[];
  matchedCriteria: string[];
  status: '신청가능' | '마감임박' | '마감';
}

export interface GeneratedDocument {
  id: string;
  templateId: string;
  title: string;
  generatedAt: string;
  fields: Record<string, string>;
  completeness: number;
  missingFields: string[];
}

// Weather
export interface WeatherForecast {
  date: string;
  condition: '맑음' | '구름많음' | '흐림' | '비' | '소나기' | '눈';
  tempHigh: number;
  tempLow: number;
  precipitation: number;
  humidity: number;
  windSpeed: number;
  icon: string;
}

export interface WeatherAlert {
  id: string;
  type: '폭우' | '폭설' | '한파' | '폭염' | '강풍';
  severity: '주의보' | '경보';
  message: string;
  startDate: string;
  endDate: string;
}

export interface FarmTask {
  id: string;
  date: string;
  title: string;
  description: string;
  type: '방제' | '관수' | '수확' | '시비' | '전정' | '관찰' | '기타';
  weatherDependent: boolean;
  recommended: boolean;
  blocked: boolean;
  blockReason?: string;
}

// Harvest
export interface GrowthData {
  date: string;
  fruitSize: number;
  colorIndex: number;
  sugarContent: number;
}

export interface YieldPrediction {
  predictedYield: number;
  unit: string;
  confidence: number;
  comparisonText: string;
  factors: string[];
}

export interface MarketPrice {
  date: string;
  price: number;
  volume: number;
}

export interface ShipTiming {
  optimalDate: string;
  expectedPrice: number;
  reasoning: string;
  alternativeDates: { date: string; price: number }[];
}

// Journal
export interface JournalEntry {
  id: string;
  date: string;
  type: '진단' | '관수' | '방제' | '수확' | '관찰' | '행정' | '기상';
  title: string;
  description: string;
  sourceModule?: string;
  photos: string[];
  sensorSnapshot?: Partial<SensorReading>;
  isAutoGenerated: boolean;
}

export interface MonthlySummary {
  month: string;
  totalIrrigations: number;
  totalDiagnoses: number;
  weatherAlertsHandled: number;
  documentsGenerated: number;
  journalEntries: number;
  highlights: string[];
}

// Scenario
export interface ScenarioEvent {
  day: number;
  module: 'iot' | 'diagnosis' | 'weather' | 'reviews' | 'documents' | 'harvest' | 'journal';
  title: string;
  description: string;
  route: string;
}

// Notification
export interface AppNotification {
  id: string;
  type: 'info' | 'warning' | 'danger' | 'success';
  title: string;
  message: string;
  timestamp: string;
  module: string;
  read: boolean;
}
