import type { JournalEntry, MonthlySummary } from '@/types';

export const JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: 'j-001', date: '2026-03-01', type: '관찰', title: '농장 등록 및 센서 설치',
    description: 'FarmOS 시스템에 농장을 등록하고 IoT 센서(토양 습도, 온도, 습도, 조도)를 설치했습니다.',
    sourceModule: 'iot', photos: [], isAutoGenerated: true,
  },
  {
    id: 'j-002', date: '2026-03-01', type: '관찰', title: '센서 정상 작동 확인',
    description: '모든 센서가 정상적으로 데이터를 전송하고 있습니다. 토양 습도 68%, 온도 12°C.',
    sourceModule: 'iot', photos: [], sensorSnapshot: { soilMoisture: 68, temperature: 12, humidity: 65 }, isAutoGenerated: true,
  },
  {
    id: 'j-003', date: '2026-03-03', type: '관수', title: '자동 관수 실행 (토양 습도 55%)',
    description: 'AI가 토양 습도 55% 이하를 감지하여 자동 관수를 실행했습니다. 30분간 관수 후 습도 72%로 회복.',
    sourceModule: 'iot', photos: [], sensorSnapshot: { soilMoisture: 55, temperature: 14, humidity: 58 }, isAutoGenerated: true,
  },
  {
    id: 'j-004', date: '2026-03-05', type: '관찰', title: '새순 생육 상태 양호',
    description: '사과나무 새순이 정상적으로 발아하고 있습니다. 올해 생육이 빠른 편입니다.',
    photos: [], isAutoGenerated: false,
  },
  {
    id: 'j-005', date: '2026-03-07', type: '진단', title: '점무늬낙엽병 AI 진단 (중증)',
    description: 'AI 진단 결과 점무늬낙엽병(중증)으로 확인되었습니다. 잎 표면 30% 이상 갈색 반점, 잎 끝 말림 증상. 신뢰도 87%. 즉시 방제가 필요합니다.',
    sourceModule: 'diagnosis', photos: ['apple-leaf-spot.jpg'], isAutoGenerated: true,
  },
  {
    id: 'j-006', date: '2026-03-07', type: '방제', title: '점무늬낙엽병 방제 실시',
    description: 'AI 추천에 따라 프로피네브 수화제(500배)를 살포했습니다. 다음 방제 예정일: 3월 14일.',
    sourceModule: 'diagnosis', photos: [], isAutoGenerated: false,
  },
  {
    id: 'j-007', date: '2026-03-10', type: '기상', title: '폭우 예보 수신 — 사전 대응',
    description: '3일 후(3/13) 폭우 예보. AI가 오늘 중 사전 방제와 배수로 점검을 권장합니다.',
    sourceModule: 'weather', photos: [], isAutoGenerated: true,
  },
  {
    id: 'j-008', date: '2026-03-10', type: '방제', title: '폭우 대비 사전 방제',
    description: '폭우 전 마지막 방제 기회. 살균제를 살포하고 배수로를 정비했습니다.',
    photos: [], isAutoGenerated: false,
  },
  {
    id: 'j-009', date: '2026-03-12', type: '진단', title: '진딧물 발견 (경증)',
    description: 'AI 진단 결과 진딧물(경증). 새순 부분에 소량 발견. 친환경 방제 우선 권장.',
    sourceModule: 'diagnosis', photos: ['apple-aphid.jpg'], isAutoGenerated: true,
  },
  {
    id: 'j-010', date: '2026-03-13', type: '기상', title: '폭우 발생 — 야외 작업 중단',
    description: '경북 내륙 폭우. 시간당 30mm 이상. 모든 야외 작업을 중단합니다.',
    sourceModule: 'weather', photos: [], isAutoGenerated: true,
  },
  {
    id: 'j-011', date: '2026-03-14', type: '관찰', title: '폭우 후 과수원 점검',
    description: '폭우 종료 후 과수원 점검. 일부 침수 흔적 있으나 심각한 피해 없음. 병해 확산 모니터링 필요.',
    photos: [], isAutoGenerated: false,
  },
  {
    id: 'j-012', date: '2026-03-15', type: '관찰', title: '리뷰 분석 리포트 생성',
    description: '온라인 리뷰 50건 분석 완료. 긍정 70%, 부정 16%, 중립 14%. 포장 개선 권장.',
    sourceModule: 'reviews', photos: [], isAutoGenerated: true,
  },
  {
    id: 'j-013', date: '2026-03-18', type: '관수', title: '정기 관수 실행',
    description: '주간 스케줄에 따른 정기 관수. 20분간 실행.',
    sourceModule: 'iot', photos: [], isAutoGenerated: true,
  },
  {
    id: 'j-014', date: '2026-03-19', type: '진단', title: '탄저병 의심 (AI 신뢰도 낮음)',
    description: 'AI 진단 결과 탄저병(심각) 의심이나 신뢰도 78%로 가드레일 발동. 전문가 확인 권장.',
    sourceModule: 'diagnosis', photos: ['apple-anthracnose.jpg'], isAutoGenerated: true,
  },
  {
    id: 'j-015', date: '2026-03-20', type: '행정', title: '재해보험 피해신고서 자동 생성',
    description: 'AI 진단 기록과 센서 로그를 기반으로 재해보험 피해신고서가 자동 생성되었습니다. 모든 필수 항목 완료.',
    sourceModule: 'documents', photos: [], isAutoGenerated: true,
  },
  {
    id: 'j-016', date: '2026-03-24', type: '진단', title: '정상 — 이상 없음',
    description: 'AI 진단 결과 이상 소견 없음. 건강한 상태입니다. 신뢰도 95%.',
    sourceModule: 'diagnosis', photos: ['apple-healthy.jpg'], isAutoGenerated: true,
  },
  {
    id: 'j-017', date: '2026-03-25', type: '관찰', title: '수확량 예측 리포트',
    description: '예상 수확량 12,500kg (작년 대비 +8%). 출하 최적 시기: 10월 중순.',
    sourceModule: 'harvest', photos: [], isAutoGenerated: true,
  },
  {
    id: 'j-018', date: '2026-03-30', type: '관찰', title: '3월 월말 정산',
    description: '이번 달 활동 요약: 자동 관수 4회, AI 진단 5회, 기상 대응 2건, 서류 1건 생성. 모든 모듈 정상 운영.',
    sourceModule: 'journal', photos: [], isAutoGenerated: true,
  },
];

export const MONTHLY_SUMMARY: MonthlySummary = {
  month: '2026년 3월',
  totalIrrigations: 4,
  totalDiagnoses: 5,
  weatherAlertsHandled: 2,
  documentsGenerated: 1,
  journalEntries: 18,
  highlights: [
    '자동 관수 시스템 정상 작동 — 토양 습도 임계값 관리 성공',
    '점무늬낙엽병 조기 발견 및 방제 완료',
    '폭우 사전 대응으로 피해 최소화',
    '리뷰 분석 기반 포장 개선 인사이트 확보',
    '재해보험 피해신고서 자동 생성 완료',
    '수확량 전년 대비 +8% 예측',
  ],
};
